### PR TITLE
Firebase Authentication is added :)

### PR DESCRIPTION
**Pull request by GeorgeET15**
Hi Sir,

I have added email and phone no authentication. Please change the color scheme according to your preference. I have also added a user profile activity. In the main directory I have a made .txt file named (logout_btn source code) please go through it. An apk file is generated in the output folder you can download and see the changes. Please accept my PR for hacktoberfest Thank you

Regards
GeorgeET15

### CODE REVIEW

**Comment by 1719pankaj** [comment]
Great!
Leme just take a good look at it 
I'll get back to you.

**Comment by 1719pankaj** [comment]
Hi,
Could you make this PR again but to the FirebaseAuth Branch instead

**Comment by GeorgeET15** [comment]
> Hi, Could you make this PR again but to the FirebaseAuth Branch instead

Do you still want me to do it or it's ok

**Comment by GeorgeET15** [comment]
Thanks a lot sir have a nice day :)

**Pull request merged**
